Добавлен ИИ для передвижения животных в ограниченеой зоне
Maweill/Escape-The-Island pull request #15
Opened 2023-02-01 15:16 UTC by Vasiliy-Enyutin

2023-02-02 17:27 UTC, Daniel-Rue reviewed
Я бы ещё добавил для объекта Animal Area полупрозрачную окружность или круг, которые будут отражать размер зоны, в которой ходят животные. То есть геймдизайнер растягивает круг как хочет, и исходя из его скейла задаётся _walkRadius. 
Ещё можно сразу добавить чтобы мобы спавнились в рандомных точках в этой окружности. А так збс, то кода не докопаться

2023-02-02 17:27 UTC, Daniel-Rue commented on Assets/_Project/Scripts/AI/AnimalArea.cs
> +        private readonly List<NavMeshAgent> _animalAgents = new();
Тут бы убрать лишнюю строчку, а то смотрится неочень + судя по документации геймобджект должен быть ниже всех

2023-02-03 07:02 UTC, Vasiliy-Enyutin commented on Assets/_Project/Scripts/AI/AnimalArea.cs
> +        private readonly List<NavMeshAgent> _animalAgents = new();
Геймобж в документации просто как пример обычного приватного поля

2023-02-03 07:04 UTC, Vasiliy-Enyutin commented
> Я бы ещё добавил для объекта Animal Area полупрозрачную окружность или круг, которые будут отражать размер зоны, в которой ходят животные, чтобы геймдизайнеру было проще заниматься расстановкой зон. То есть чтобы он растягивал круг как хочет, и исходя из его скейла задавался_walkRadius. Ещё можно сразу добавить чтобы мобы спавнились в рандомных точках в этой окружности. А так збс, до кода не докопаться

Update: Это и так есть, можно нажать на Area в иерархии после запуска игры и будет видна зона, в которой может ходить животное. Работает только после запуска игры, т.к. мы получаем WalkArea с помощью дескриптора, изначально эта переменная не определена

2023-02-03 07:05 UTC, Vasiliy-Enyutin commented on Assets/_Project/Scripts/AI/AnimalArea.cs
> +        private readonly List<NavMeshAgent> _animalAgents = new();
Пробелом разделил для удобства, что сверху поля, которые мы "заполним" через Init с помощью дескриптора

2023-02-03 07:17 UTC, Daniel-Rue commented
Ок, попозже посмотрю как это работает, а рандомный спавн оформишь?> > Я бы ещё добавил для объекта Animal Area полупрозрачную окружность или круг, которые будут отражать размер зоны, в которой ходят животные, чтобы геймдизайнеру было проще заниматься расстановкой зон. То есть чтобы он растягивал круг как хочет, и исходя из его скейла задавался_walkRadius. Ещё можно сразу добавить чтобы мобы спавнились в рандомных точках в этой окружности. А так збс, до кода не докопаться
> 
> 
> 
> Update: Это и так есть, можно нажать на Area в иерархии после запуска игры и будет видна зона, в которой может ходить животное. Работает только после запуска игры, т.к. мы получаем WalkArea с помощью дескриптора, изначально эта переменная не определена

2023-02-03 07:23 UTC, Daniel-Rue commented
Ок, попозже посмотрю как это работает, а рандомный спавн оформишь?

2023-02-03 07:44 UTC, Vasiliy-Enyutin commented
> Ок, попозже посмотрю как это работает, а рандомный спавн оформишь?

Update: А зачем рандомный спавн. Зоны то "геймдизайнер" расставляет. Тип животного выставил и зону разместил

2023-02-03 15:34 UTC, Maweill requested changes
Почему решил не делать отдельный скрипт под животных? В чем идея, что AnimalArea контролирует поведение животных?

2023-02-03 15:34 UTC, Maweill commented on Assets/_Project/Scripts/AI/AnimalArea.cs
> +                _animalAgents.Add(Instantiate(_animalPrefab, transform).GetComponent<NavMeshAgent>());
Все игровые объекты создаем через assetProvider, потому что он инжектит зависимости при создании

2023-02-03 15:34 UTC, Maweill commented on Assets/_Project/Scripts/Descriptors/Animals/AnimalDescriptor.cs
> +    public class AnimalDescriptor : ScriptableObject
AnimalAreaDescriptor? На AnimalDescriptor как-то не похоже

2023-02-03 15:34 UTC, Maweill commented on Assets/_Project/Scripts/EnvironmentResources/Resource.cs
> +        private const float ITEM_DROP_RADIUS = 1.5f;
константы выше всех должны быть

2023-02-03 15:34 UTC, Maweill commented on Assets/_Project/Scripts/EnvironmentResources/Resource.cs
> +            Instantiate(_resourceItemPrefab, spawnPoint, Quaternion.identity);
assetProvider

2023-02-03 15:34 UTC, Maweill commented on Assets/_Project/Scripts/EnvironmentResources/Resource.cs
> +        private const float ITEM_DROP_RADIUS = 1.5f;
они по очереди инициализации самые первые готовы

2023-02-03 17:29 UTC, Vasiliy-Enyutin commented
ResourceMiner и ItemCollector, возможно, стоит объединить

2023-02-05 05:57 UTC, Daniel-Rue requested changes

2023-02-05 05:57 UTC, Daniel-Rue commented on Assets/_Project/Scripts/PlayerLogic/InventoryModel.cs
> +        }
А где проверка что _items[item] может быть меньше quantity? Я бы сделал публичный метод CheckItemQuantity, в который передаётся quantity и ItemDescriptor, а метод проверяет достаточно ли данных предметов инвентаре, и только после его вызова совершать _items[item] -= quantity;

2023-02-05 05:57 UTC, Daniel-Rue commented on Assets/_Project/Scripts/PlayerLogic/InventoryModel.cs
> +        }
И вообще я бы AddItem и RemoveItem сделал бы bool. Потому что, например, при строительстве здания, я хочу из моей функции вызвать RemoveItem. Если предметов достаточно, то вернётся true и здание подставится, если folse - нет. В AddItem тоже самое только при собирательстве, вдруг инвентарь заполнится?

2023-02-05 06:13 UTC, Daniel-Rue commented
Ещё бы добавить визуализацию собранных айтемов в канвасе, чтобы проще было тестировать строительство

2023-02-05 09:07 UTC, Vasiliy-Enyutin commented on Assets/_Project/Scripts/PlayerLogic/InventoryModel.cs
> +        }
Всё хуйня

2023-02-05 14:25 UTC, Maweill requested changes

2023-02-05 14:25 UTC, Maweill commented on Assets/_Project/Scripts/Descriptors/Resources/ResourceDescriptor.cs
> +        public ItemDescriptor ItemDescriptor = null!;
Мб сразу списком сделать? Но пока необязательно конечно, смотри сам

2023-02-05 14:25 UTC, Maweill commented on Assets/_Project/Scripts/GameInitializer.cs
> +				animalArea.Init(areaDescriptor.AnimalPrefab, areaDescriptor.WalkRadius, areaDescriptor.PositionsChangeDelay, areaDescriptor.AnimalsNumber);
Вот я задумался над тем, что у нас на работе в Init бы поместили сразу дескриптор и там бы уже сохранили в нужные поля. Но я не уверен

2023-02-05 14:25 UTC, Maweill commented on Assets/_Project/Scripts/PlayerLogic/InventoryModel.cs
> +            _items[item] -= quantity;
тут бы ворнинг, если вычитаемое кол-во окажется больше существующего

2023-02-05 14:25 UTC, Maweill commented on Assets/_Project/Scripts/PlayerLogic/InventoryService.cs
> +
.

2023-02-05 14:25 UTC, Maweill commented on Assets/_Project/Scripts/PlayerLogic/PlayerCollisionDetector.cs
> +            if (other.TryGetComponent(out Item item))
else if или return на 24 строке. нет же смысла делать вторую проверку, если первая сработала

2023-02-05 14:25 UTC, Maweill commented on Assets/_Project/Scripts/PlayerLogic/PlayerCollisionDetector.cs
> +            if (other.TryGetComponent(out Item item))
аналогично выше

2023-02-05 14:37 UTC, Vasiliy-Enyutin commented on Assets/_Project/Scripts/Descriptors/Resources/ResourceDescriptor.cs
> +        public ItemDescriptor ItemDescriptor = null!;
Думаю, потом. Там и шансы выпадения итемов тогда продумывать уже. На этом этапе несущественно, считаю

2023-02-05 14:37 UTC, Vasiliy-Enyutin commented on Assets/_Project/Scripts/GameInitializer.cs
> +				animalArea.Init(areaDescriptor.AnimalPrefab, areaDescriptor.WalkRadius, areaDescriptor.PositionsChangeDelay, areaDescriptor.AnimalsNumber);
Говоришь, передаём сразу поля. Откуда берутся без разницы

2023-02-05 14:45 UTC, Vasiliy-Enyutin commented on Assets/_Project/Scripts/PlayerLogic/PlayerCollisionDetector.cs
> +            if (other.TryGetComponent(out Item item))
Здесь уже нужно, чтобы обнулять и в ResourceMiner и в ItemCollector текущие ресурсы/итемы. Т.к. можно обнулить только что-то одно и может остаться в каком-либо из этих скриптов незануленное поле. Допустим, отошли от ресурса и итема одновременно. Оба не должны быть записаны в поля вышеуказанных скриптов

2023-02-05 14:58 UTC, Maweill commented on Assets/_Project/Scripts/PlayerLogic/PlayerCollisionDetector.cs
> +            if (other.TryGetComponent(out Item item))
так коллайдер то один у тебя

2023-02-05 15:14 UTC, Maweill approved these changes

2023-02-05 15:57 UTC, merged