Добавил систему строительства
Maweill/Escape-The-Island pull request #9
Opened 2023-01-29 15:42 UTC by Daniel-Rue

Сделал сетку размещения зданий, добавил индикатор для определения занятости ячейки для зданий.

2023-01-29 17:38 UTC, Maweill requested changes

2023-01-29 17:38 UTC, Maweill commented on Assets/Scripts/Building.cs
> +    }
MainRenderer.material.color = available ? Color.green : Color.red;

2023-01-29 17:38 UTC, Maweill commented on Assets/Scripts/Building.cs
> +                else Gizmos.color = new Color(1f, 0.68f, 0f, 0.3f);
Вынести в начало файла что-то типа ```private const RED_COLOR = new Color(1f, 0.68f, 0f, 0.3f);```

2023-01-29 17:38 UTC, Maweill commented on Assets/Scripts/Building.cs
> +    public Vector2Int Size = Vector2Int.one;
Если этим кто-то пользуется извне, то нужно свойство с "backing field". Само поле должно быть приватным с serialize field атрибутом

2023-01-29 17:38 UTC, Maweill commented on Assets/Scripts/BuildingsGrid.cs
> +    public Vector2Int GridSize = new Vector2Int(10, 10);
.

2023-01-29 17:38 UTC, Maweill commented on Assets/Scripts/BuildingsGrid.cs
> +        if (flyingBuilding != null)
"invert if" в райдере на alt+Enter

2023-01-30 09:37 UTC, Daniel-Rue commented on Assets/Scripts/Building.cs
> +    }
Исправил

2023-01-30 09:37 UTC, Daniel-Rue commented on Assets/Scripts/Building.cs
> +                else Gizmos.color = new Color(1f, 0.68f, 0f, 0.3f);
Исправил

2023-01-30 09:37 UTC, Daniel-Rue commented on Assets/Scripts/Building.cs
> +    public Vector2Int Size = Vector2Int.one;
Исправил

2023-01-30 09:37 UTC, Daniel-Rue commented on Assets/Scripts/BuildingsGrid.cs
> +    public Vector2Int GridSize = new Vector2Int(10, 10);
Исправил

2023-01-30 09:37 UTC, Daniel-Rue commented on Assets/Scripts/BuildingsGrid.cs
> +        if (flyingBuilding != null)
Исправил

2023-01-30 15:08 UTC, Maweill requested changes
Также убрать все "=>" на фигурные скобки. if сделать тоже с фигурными и т.д. В одну строку ифы не пишем. Конфиг лежит в тг

2023-01-30 15:08 UTC, Maweill commented on Assets/_Project/Scripts/Building.cs
> +        mainRenderer.material.color = available ? Color.green : Color.red;
можно вынести в свойство Color с логикой в set, так как дважды используется

2023-01-30 15:08 UTC, Maweill commented on Assets/_Project/Scripts/BuildingsGrid.cs
> +    private static void GetPlacementCoordinates(Ray ray, float position, out int x, out int y)
райдер автоматом такое любит делать, но статик тут не нужен. ни на что не влияет тут

2023-01-30 16:21 UTC, Daniel-Rue commented on Assets/_Project/Scripts/Building.cs
> +        mainRenderer.material.color = available ? Color.green : Color.red;
Не понял как сделать

2023-01-30 17:52 UTC, Maweill commented on Assets/_Project/Scripts/Building.cs
> +        mainRenderer.material.color = available ? Color.green : Color.red;
```private Color MeshColor {set { mainRenderer.material.color = value; } }```

2023-01-31 11:32 UTC, Maweill requested changes
микро правки остались)

2023-01-31 11:32 UTC, Maweill commented on Assets/_Project/Scripts/BuildingsGrid.cs
> +        if (_flyingBuilding == null)
фигурные скобки тут и в остальных местах ниже

2023-01-31 11:32 UTC, Maweill commented on Assets/_Project/Scripts/BuildingsGrid.cs
> -        {
тут тоже скобки

2023-01-31 11:32 UTC, Maweill commented on Assets/_Project/Scripts/BuildingsGrid.cs
> +        if (_flyingBuilding == null)
первая скобка на одной строке с ифом, вторая как обычно

2023-01-31 11:32 UTC, Maweill commented on Assets/_Project/Scripts/BuildingsGrid.cs
> +    private Building? _flyingBuilding;
супер!

2023-01-31 11:32 UTC, Maweill commented on Assets/_Project/Scripts/Building.cs
> +        _mainRenderer.material.color = Color.white;
тут тоже на MeshColor забыл заменить

2023-02-02 07:31 UTC, Maweill commented on Assets/_Project/Scripts/CameraRaycaster.cs
> +    [SerializeField] private float distanceToBackground = 100f;
тег сверху должен быть, видимо райдер автоматом исправил - измени в настройках "Code Style" вроде

2023-02-02 07:32 UTC, Maweill commented on Assets/_Project/Scripts/CameraRaycaster.cs
>      public event OnLayerChange onLayerChange; // instantiate an observer set
тут не понял, зачем нужен делегат

2023-02-02 07:33 UTC, Daniel-Rue commented on Assets/_Project/Scripts/CameraRaycaster.cs
>      public event OnLayerChange onLayerChange; // instantiate an observer set
Нииииэт!!! Не смотри туда, там кал временный

2023-02-02 07:33 UTC, Maweill commented on Assets/_Project/Scripts/CameraRaycaster.cs
>          print("I handle it!");
давай пока Debug.Log юзать, а потом будем кастомный логер использовать

2023-02-02 07:40 UTC, Maweill requested changes
Пару комментов вне ревью оставил

2023-02-02 07:40 UTC, Maweill commented on Assets/_Project/Scripts/CameraRaycaster.cs
>          Layer.Walkable
Скрипт видимо чужой. Если берешь что-то из инета, то под стиль кода проекта его все равно нужно адаптировать. В идеале если прям целый скрипт берешь, то оставлять ссылку на источник, чтобы другие могли ознакомиться, если возникнут вопросы

2023-02-02 07:40 UTC, Maweill commented on Assets/_Project/Scripts/CameraRaycaster.cs
>          Layer.Walkable
Короче не должно быть понятно, что скрипт не местный

2023-02-03 10:41 UTC, Daniel-Rue commented on Assets/_Project/Scripts/CameraRaycaster.cs
>      public event OnLayerChange onLayerChange; // instantiate an observer set
Это Action, только расписанный в две строки. Исправил

2023-02-03 11:18 UTC, Daniel-Rue commented on Assets/_Project/Scripts/CameraRaycaster.cs
>          Layer.Walkable
Он мой

2023-02-03 15:43 UTC, Maweill requested changes
Думаю, это последнее)

2023-02-03 15:43 UTC, Maweill commented on Assets/_Project/Scripts/BuildingsGrid.cs
> +            _flyingBuilding = Instantiate(buildingPrefab);
для спавна игровых объектов используем assetProvider, потому что он инжектит зависимости при создании

2023-02-03 15:43 UTC, Maweill commented on Assets/_Project/Scripts/BuildingsGrid.cs
> +            x = (int)Mathf.Floor(position.x);
пробел после (int) поставь, пж
напишу в гайдах об этом. это как после операторов пробел ставить нужно, а то в кучу сливается немного

2023-02-03 15:43 UTC, Maweill commented on Assets/_Project/Scripts/BuildingsGrid.cs
> +            int localY = globalY - (int)_originPoint.transform.position.z;
и тут (int)

2023-02-03 15:43 UTC, Maweill commented on Assets/_Project/Scripts/CameraRaycaster.cs
> +            // Look for and return priority layer hit
Давайте комменты на русском писать, если они нужны

2023-02-03 15:43 UTC, Maweill commented on Assets/_Project/Scripts/CursorAffordance.cs
> +                    Debug.LogError("Error cursor");
Поинформативней бы лог. Прописать бы что хотели сделать и значение newLayer. Логи оформляем так "Trying to do smth but layer is invalid. layer={newLayer}"

2023-02-04 07:25 UTC, Maweill approved these changes

2023-02-04 07:27 UTC, merged